version: '3'

services:
  phaser-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: phaser-container
    ports:
      - '3000'
    volumes:
      - ./p04-reto:/usr/src/app
    stdin_open: true
